# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.3-stretch-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/aqa-python

    filters:
      branches:
        only: /.*/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          when: always

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install allure
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev
          when: always

      - run:
          name: aqa-python run tests
          command: |
            . venv/bin/activate
            mkdir allure-results/
            mkdir allure-report/
            pytest -n4 --alluredir=allure-results
          when: always

      - store_test_results:
          path: allure-results

      - run:
          name: show allure report
          command: |
            allure generate -c allure-results -o allure-report
          when: always

      - store_artifacts:
          path: allure-report
          destination: allure-report
